services:
  garage:
    image: ghcr.io/dchakin/garage-nuxt-project:latest
    container_name: garage
    restart: unless-stopped
    environment:
      DB_FILE_NAME: /app/data/garage.db
      NUXT_SESSION_PASSWORD: ${NUXT_SESSION_PASSWORD}
      NUXT_SESSION_COOKIE_SECURE: "true"
      NUXT_PUBLIC_VAPID_PUBLIC_KEY: ${NUXT_PUBLIC_VAPID_PUBLIC_KEY}
      NUXT_VAPID_PRIVATE_KEY: ${NUXT_VAPID_PRIVATE_KEY}
      NUXT_VAPID_SUBJECT: ${NUXT_VAPID_SUBJECT}
      NODE_ENV: production
    volumes:
      - ./data:/app/data
    ports:
      - "127.0.0.1:3000:3000"
